#pragma once

#ifdef CLIENT

enum OBJID { GAMEOBJ, OBJ_END };

#endif



#ifdef TOOL

enum RENDER { RENDER_GRID, RENDER_ANI, RENDER_BACK, RENDER_COLL, RENDER_END };
enum LAYER_TYPE { LAYER_BACK, LAYER_TILE, LAYER_END };
enum COLL_TYPE { COLL_ALL, COLL_JUMP, COLL_INTERACT, COLL_END };

#endif // TOOL