#pragma once

#ifdef CLIENT

enum OBJID { MAP, PLAYER, MONSTER, EFFECT, GAMEOBJ, OBJ_END };

#endif



#ifdef TOOL

enum RENDER { RENDER_GRID, RENDER_ANI, RENDER_BACK, RENDER_COLL, RENDER_END };
enum LAYER_TYPE { LAYER_BACK, LAYER_OBJECT, LAYER_TILE, LAYER_COLL, LAYER_END };

#endif // TOOL